//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeMaker_v4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public int cusID { get; set; }
        public int odID { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal totalPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
